spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: r1
              uri: lb://KEYNOTE-SERVICE
              predicates:
                - Path= /api/keynotes/**
            - id: r2
              uri: lb://CONFERENCE-SERVICE
              predicates:
                - Path= /api/conferences/**
            - id: r3
              uri: lb://CONFERENCE-SERVICE
              predicates:
                - Path= /api/reviews/**
