spring.application.name=gateway-service
server.port=8081
spring.cloud.config.enabled=false
spring.cloud.discovery.enabled=true
eureka.client.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
management.endpoints.web.exposure.include=health,refresh
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
spring.cloud.config.discovery.enabled=true

# OAuth2 Client Configuration
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/conference-realm
spring.security.oauth2.client.registration.keycloak.client-id=gateway-client
spring.security.oauth2.client.registration.keycloak.client-secret=your-client-secret
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# OAuth2 Resource Server Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/conference-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/conference-realm/protocol/openid-connect/certs

