spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: r1
              uri: http://localhost:8085
              predicates:
                - Path= /api/keynotes/**
            - id: r2
              uri: http://localhost:8086
              predicates:
                - Path= /api/conferences/**
            - id: r3
              uri: http://localhost:8086
              predicates:
                - Path= /api/reviews/**
